theme: jekyll-theme-minimal
picture: ![image](https://user-images.githubusercontent.com/59896948/99458352-acd6f300-292c-11eb-94d7-07ce8299fb99.png)
title: Welcome to the akramla’s homepage! 
description: Feel free to bookmark this to keep an eye on my project updates
